### ISSUE TITLE
Error in instructions under "Using the Generator"

### ISSUE THREAD

**Issue by gordonleacock** [projecthydra-labs/browse-everything#106]
Hope I'm not out of line adding this (new to github), but in the instructions under "Using the Generator" it documents "rails g browse_anything:config" where I think it should say "rails g browse_everything:config"

Regards,

Gordon Leacock, University of Michigan (gordonl@umich.edu)

**Comment by mjgiarlo** [comment]
@gordonleacock [Here](https://github.com/projecthydra-labs/browse-everything/wiki/Configuring-browse-everything), you mean? If so, fixed! Thanks, Gordon.

**Comment by gordonleacock** [comment]
That was it, thanks for the quick fix!


Gordon Leacock
Application Programmer
UM Library Digital Production Services
Room 301 Harlan Hatcher Graduate Library
University of Michigan, Ann Arbor
