### ISSUE TITLE
Don't overwrite click event for all checkboxes on the page

### ISSUE THREAD

**Issue by hectorcorrea** [projecthydra-labs/browse-everything#109]
Limit the wiring of the `change` event for checkboxes to only the ones that Browse Everything owns. The current code [1] wires all checkboxed on the page: 

```
   $(document).on 'change', 'input:checkbox', (event) ->
```

Perhaps we could limit the checkboxes by CSS class.

[1] https://github.com/projecthydra-labs/browse-everything/blob/master/app/assets/javascripts/browse_everything/behavior.js.coffee#L290

**Comment by awead** [comment]
@hectorcorrea yeah, my bad. There's one there already, I just forgot to add it to the listener:
https://github.com/projecthydra-labs/browse-everything/blob/master/app/views/browse_everything/_file.html.erb#L27
