### ISSUE TITLE
Why does the box api take so very long?

### ISSUE THREAD

**Issue by cam156** [projecthydra-labs/browse-everything#112]
When I load files via dropbox they load almost instantaneously.
When I load files via box it times out if the user has too many files.

2015-10-20 13:46:24 -0400 (26550) 
ActionView::Template::Error (Connection timed out - connect(2) for "api.box.com" port 443):
    13:         <th role="columnheader">Modified</th>
    14:       </tr>
    15:     </thead>
    16:     <% provider.contents(browse_path).each_with_index do |file,index| %>
    17:       <% if is_acceptable?(file) %>
    18:         <%= render :partial => 'file', :locals => { :file => file, :index => index, 
    19:           :path => browse_everything_engine.contents_path(provider_name,file.id), :parent => params[:parent] } %>
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `open'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:878:in `connect'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:852:in `start'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/net/http.rb:1375:in `request'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request_with_newrelic_trace'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent.rb:431:in `disable_all_tracing'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newrelic_trace'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace'
  ruby-box (1.15.0) lib/ruby-box/session.rb:74:in `request'
  ruby-box (1.15.0) lib/ruby-box/session.rb:50:in `get'
  ruby-box (1.15.0) lib/ruby-box/item.rb:68:in `reload_meta'
  ruby-box (1.15.0) lib/ruby-box/client.rb:20:in `folder_by_id'
  ruby-box (1.15.0) lib/ruby-box/client.rb:15:in `root_folder'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/lib/browse_everything/driver/box.rb:28:in `contents'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/app/views/browse_everything/_files.html.erb:16:in `__opt_heracles_deploy_scholarsphere_shared_bundle_ruby_______bundler_gems_browse_everything_e_c__be__ebc_app_views_browse_everything__files_html_erb___4373759672665732295_70293432970260'
  actionview (4.2.2) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.2) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.2) lib/action_view/template.rb:143:in `render'
  actionview (4.2.2) lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
  actionview (4.2.2) lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
  actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.2) lib/action_view/renderer/partial_renderer.rb:309:in `render'
  actionview (4.2.2) lib/action_view/renderer/renderer.rb:47:in `render_partial'
  actionview (4.2.2) lib/action_view/helpers/rendering_helper.rb:35:in `render'
  haml (4.0.7) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/app/views/browse_everything/show.html.erb:3:in `__opt_heracles_deploy_scholarsphere_shared_bundle_ruby_______bundler_gems_browse_everything_e_c__be__ebc_app_views_browse_everything_show_html_erb___3424994638726784695_70293403219300'
  actionview (4.2.2) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.2) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.2) lib/action_view/template.rb:143:in `render'
  actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.2) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.2) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.2) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.2) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.2) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.2) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.2) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.2) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.2) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.2) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.2) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.2) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /opt/heracles/deploy/.rbenv/versions/2.2.3/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.2) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:43:in `render'
  /opt/heracles/deploy/scholarsphere/shared/bundle/ruby/2.2.0/bundler/gems/browse-everything-e7c83be25ebc/app/controllers/browse_everything_controller.rb:14:in `show'
  actionpack (4.2.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.2) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.2) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.2) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.2) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.2) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.2) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.2) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.2) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `call'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.2) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.2) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.2) lib/action_dispatch/routing/route_set.rb:819:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack-maintenance (2.0.0) lib/rack/maintenance.rb:19:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/flash.rb:260:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.2.2) lib/active_record/query_cache.rb:36:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activerecord (4.2.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  active-fedora (9.4.0) lib/active_fedora/ldp_cache.rb:26:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.2) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
  activesupport (4.2.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.2) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.2) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.2) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  activesupport (4.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  actionpack (4.2.2) lib/action_dispatch/middleware/ssl.rb:24:in `call'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  railties (4.2.2) lib/rails/engine.rb:518:in `call'
  railties (4.2.2) lib/rails/application.rb:164:in `call'
  railties (4.2.2) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.2) lib/rails/railtie.rb:194:in `method_missing'
  newrelic_rpm (3.13.0.299) lib/new_relic/agent/instrumentation/middleware_tracing.rb:67:in `call'
  /usr/lib/ruby/1.8/phusion_passenger/rack/thread_handler_extension.rb:78:in `process_request'
  /usr/lib/ruby/1.8/phusion_passenger/request_handler/thread_handler.rb:136:in `accept_and_process_next_request'
  /usr/lib/ruby/1.8/phusion_passenger/request_handler/thread_handler.rb:97:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/request_handler.rb:439:in `block (3 levels) in start_threads'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:96:in `block in create_thread_and_abort_on_exception'

**Comment by cam156** [comment]
I'll try to get a PR in next week, but if someone wants to take a stab at it...

The issue is this line https://github.com/projecthydra-labs/browse-everything/blob/master/lib/browse_everything/driver/box.rb#L29

That is only returning the name, and then we are making separate api calls for all the other items.  If that line gets changed to the code below it is almost instantaneous. 

```
result += folder.items(99999,0,['name','size', 'created_at', 'description']).collect do |f|
```

**Comment by cam156** [comment]
Check out here for the why: https://github.com/attachmentsme/ruby-box#only-some-fields-are-available

**Comment by mbklein** [comment]
Got it. I'll make this change and release in a couple hours. This has been
making me NUTS.

Michael
